services:
  giterdone:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: giterdone
    ports:
      - "7860:7860"
    env_file:
      - .env
    image: giterdone/app
    volumes:
      - $HOME/.aws/credentials:/home/user/.aws/credentials:ro
      - ./src/:/home/user/app/src/
