services:
  wrong-number:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wrong-number
    ports:
      - "7860:7860"
    env_file:
      - .env
    image: wrongnumber/app
    volumes:
      - $HOME/.aws/credentials:/home/user/.aws/credentials:ro
      - ./src/:/home/user/app/src/
