services:
  giterdone:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: giterdone
    ports:
      - "7860:7860"
    env_file:
      - .env
    image: giterdone/app
    volumes:
      - ${PWD}/.env:/home/user/app/.env:ro
      - ./src/:/home/user/app/src/
